title: Chenyang Zhao
name: Chenyang Zhao
position: MSci Imperial College London
email: cz2922@ic.ac.uk

description: >-
  I am a final-year MSci student in Mathematics at [Imperial College London](https://www.imperial.ac.uk/), working in algebraic geometry, especially deformation theory, Hilbert schemes, moduli problems, and computational methods.

baseurl: "" # for GitHub Pages
url: "https://www.felixzhao.com"

twitter_username: ChenyangZh61334
github_username: chenyangzhaoicl
google_scholar: _2HOwMIAAAAJ
last_updated: 23 June 2026

# ✅ 使用官方推荐方式设置主题
remote_theme: jekyll/minima

plugins:
  - jekyll-feed

sass:
  style: compact
